
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_employee(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 312)
        Dialog.setMinimumSize(QtCore.QSize(400, 312))
        Dialog.setMaximumSize(QtCore.QSize(400, 312))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.f_name = QtWidgets.QLineEdit(Dialog)
        self.f_name.setGeometry(QtCore.QRect(40, 30, 311, 25))
        self.f_name.setObjectName("f_name")
        self.m_init = QtWidgets.QLineEdit(Dialog)
        self.m_init.setGeometry(QtCore.QRect(40, 80, 311, 25))
        self.m_init.setObjectName("m_init")
        self.l_name = QtWidgets.QLineEdit(Dialog)
        self.l_name.setGeometry(QtCore.QRect(40, 130, 311, 25))
        self.l_name.setObjectName("l_name")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 190, 71, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 91, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 91, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 91, 17))
        self.label_3.setObjectName("label_3")
        self.age = QtWidgets.QLabel(Dialog)
        self.age.setGeometry(QtCore.QRect(280, 170, 91, 17))
        self.age.setObjectName("age")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(40, 160, 96, 23))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 190, 96, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 220, 96, 23))
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Employee"))
        self.label.setText(_translate("Dialog", "First Name"))
        self.label_2.setText(_translate("Dialog", "Middle Initial"))
        self.label_3.setText(_translate("Dialog", "Last Name"))
        self.age.setText(_translate("Dialog", "Age"))
        self.radioButton.setText(_translate("Dialog", "Pilot"))
        self.radioButton_2.setText(_translate("Dialog", "Cabin Crew"))
        self.radioButton_3.setText(_translate("Dialog", "Technician"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_add_fleet()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
