# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'airline_panel.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_airline_panel(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(671, 525)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 651, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.dashboard_tab = QtWidgets.QWidget()
        self.dashboard_tab.setObjectName("dashboard_tab")
        self.dash_flight_table = QtWidgets.QTableWidget(self.dashboard_tab)
        self.dash_flight_table.setGeometry(QtCore.QRect(20, 30, 611, 211))
        self.dash_flight_table.setObjectName("dash_flight_table")
        self.dash_flight_table.setColumnCount(0)
        self.dash_flight_table.setRowCount(0)
        self.label = QtWidgets.QLabel(self.dashboard_tab)
        self.label.setGeometry(QtCore.QRect(30, 270, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dash_finances_label = QtWidgets.QLabel(self.dashboard_tab)
        self.dash_finances_label.setGeometry(QtCore.QRect(190, 270, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dash_finances_label.setFont(font)
        self.dash_finances_label.setObjectName("dash_finances_label")
        self.label_3 = QtWidgets.QLabel(self.dashboard_tab)
        self.label_3.setGeometry(QtCore.QRect(30, 310, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dash_employee_label = QtWidgets.QLabel(self.dashboard_tab)
        self.dash_employee_label.setGeometry(QtCore.QRect(190, 310, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dash_employee_label.setFont(font)
        self.dash_employee_label.setObjectName("dash_employee_label")
        self.dash_fleet_label = QtWidgets.QLabel(self.dashboard_tab)
        self.dash_fleet_label.setGeometry(QtCore.QRect(530, 270, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dash_fleet_label.setFont(font)
        self.dash_fleet_label.setObjectName("dash_fleet_label")
        self.label_6 = QtWidgets.QLabel(self.dashboard_tab)
        self.label_6.setGeometry(QtCore.QRect(400, 270, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dash_planes_label = QtWidgets.QLabel(self.dashboard_tab)
        self.dash_planes_label.setGeometry(QtCore.QRect(530, 310, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dash_planes_label.setFont(font)
        self.dash_planes_label.setObjectName("dash_planes_label")
        self.label_8 = QtWidgets.QLabel(self.dashboard_tab)
        self.label_8.setGeometry(QtCore.QRect(400, 310, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.dashboard_tab)
        self.label_9.setGeometry(QtCore.QRect(400, 350, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.dash_busses_label = QtWidgets.QLabel(self.dashboard_tab)
        self.dash_busses_label.setGeometry(QtCore.QRect(530, 350, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dash_busses_label.setFont(font)
        self.dash_busses_label.setObjectName("dash_busses_label")
        self.label_11 = QtWidgets.QLabel(self.dashboard_tab)
        self.label_11.setGeometry(QtCore.QRect(30, 350, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.dash_activeR_label = QtWidgets.QLabel(self.dashboard_tab)
        self.dash_activeR_label.setGeometry(QtCore.QRect(190, 350, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dash_activeR_label.setFont(font)
        self.dash_activeR_label.setObjectName("dash_activeR_label")
        self.label_13 = QtWidgets.QLabel(self.dashboard_tab)
        self.label_13.setGeometry(QtCore.QRect(30, 390, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.dash_passenger_label = QtWidgets.QLabel(self.dashboard_tab)
        self.dash_passenger_label.setGeometry(QtCore.QRect(190, 390, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dash_passenger_label.setFont(font)
        self.dash_passenger_label.setObjectName("dash_passenger_label")
        self.label_15 = QtWidgets.QLabel(self.dashboard_tab)
        self.label_15.setGeometry(QtCore.QRect(400, 390, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.dash_flights_label = QtWidgets.QLabel(self.dashboard_tab)
        self.dash_flights_label.setGeometry(QtCore.QRect(530, 390, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dash_flights_label.setFont(font)
        self.dash_flights_label.setObjectName("dash_flights_label")
        self.label_2 = QtWidgets.QLabel(self.dashboard_tab)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 91, 17))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.dashboard_tab, "")
        self.fleet_tab = QtWidgets.QWidget()
        self.fleet_tab.setObjectName("fleet_tab")
        self.fleet_table = QtWidgets.QTableWidget(self.fleet_tab)
        self.fleet_table.setGeometry(QtCore.QRect(20, 10, 611, 381))
        self.fleet_table.setObjectName("fleet_table")
        self.fleet_table.setColumnCount(0)
        self.fleet_table.setRowCount(0)
        self.schedule_maint_button = QtWidgets.QPushButton(self.fleet_tab)
        self.schedule_maint_button.setGeometry(QtCore.QRect(220, 410, 141, 25))
        self.schedule_maint_button.setObjectName("schedule_maint_button")
        self.add_fleet_button = QtWidgets.QPushButton(self.fleet_tab)
        self.add_fleet_button.setGeometry(QtCore.QRect(550, 410, 80, 25))
        self.add_fleet_button.setObjectName("add_fleet_button")
        self.fleet_date_time = QtWidgets.QDateTimeEdit(self.fleet_tab)
        self.fleet_date_time.setGeometry(QtCore.QRect(20, 410, 194, 26))
        self.fleet_date_time.setObjectName("fleet_date_time")
        self.tabWidget.addTab(self.fleet_tab, "")
        self.maintenance_tab = QtWidgets.QWidget()
        self.maintenance_tab.setObjectName("maintenance_tab")
        self.maintenance_table = QtWidgets.QTableWidget(self.maintenance_tab)
        self.maintenance_table.setGeometry(QtCore.QRect(20, 10, 611, 381))
        self.maintenance_table.setObjectName("maintenance_table")
        self.maintenance_table.setColumnCount(0)
        self.maintenance_table.setRowCount(0)
        self.tabWidget.addTab(self.maintenance_tab, "")
        self.employee_tab = QtWidgets.QWidget()
        self.employee_tab.setObjectName("employee_tab")
        self.employee_table = QtWidgets.QTableWidget(self.employee_tab)
        self.employee_table.setGeometry(QtCore.QRect(20, 10, 611, 381))
        self.employee_table.setObjectName("employee_table")
        self.employee_table.setColumnCount(0)
        self.employee_table.setRowCount(0)
        self.add_employee_button = QtWidgets.QPushButton(self.employee_tab)
        self.add_employee_button.setGeometry(QtCore.QRect(550, 410, 80, 25))
        self.add_employee_button.setObjectName("add_employee_button")
        self.tabWidget.addTab(self.employee_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 671, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Airline Panel"))
        self.label.setText(_translate("MainWindow", "Finances"))
        self.dash_finances_label.setText(_translate("MainWindow", "$$$$"))
        self.label_3.setText(_translate("MainWindow", "Employees"))
        self.dash_employee_label.setText(_translate("MainWindow", "$$$$"))
        self.dash_fleet_label.setText(_translate("MainWindow", "$$$$"))
        self.label_6.setText(_translate("MainWindow", "Fleet Size"))
        self.dash_planes_label.setText(_translate("MainWindow", "$$$$"))
        self.label_8.setText(_translate("MainWindow", "Planes"))
        self.label_9.setText(_translate("MainWindow", "Busses"))
        self.dash_busses_label.setText(_translate("MainWindow", "$$$$"))
        self.label_11.setText(_translate("MainWindow", "Active Routes"))
        self.dash_activeR_label.setText(_translate("MainWindow", "$$$$"))
        self.label_13.setText(_translate("MainWindow", "Passenger Served"))
        self.dash_passenger_label.setText(_translate("MainWindow", "$$$$"))
        self.label_15.setText(_translate("MainWindow", "Total Flights"))
        self.dash_flights_label.setText(_translate("MainWindow", "$$$$"))
        self.label_2.setText(_translate("MainWindow", "Flights"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dashboard_tab), _translate("MainWindow", "Dashboard"))
        self.schedule_maint_button.setText(_translate("MainWindow", "Schedule Maintenance"))
        self.add_fleet_button.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fleet_tab), _translate("MainWindow", "Fleet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.maintenance_tab), _translate("MainWindow", "Maintenance"))
        self.add_employee_button.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.employee_tab), _translate("MainWindow", "Employees"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_airline_panel()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
